### ISSUE TITLE
En validation de scan multiple (traitement des valeurs scanées), erreur SQL

### ISSUE THREAD

**Issue by equinton** [Irstea/collec#60]
42703 SQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne \xc2\xab locality \xc2\xbb n'existe pas\nLINE 20:         metadata::varchar, locality\n                                    ^\nHINT:  Il existe une colonne nomm\xc3\xa9e \xc2\xab locality \xc2\xbb pour la table \xc2\xab *SELECT* 1 \xc2\xbb mais elle ne peut pas \xc3\xaatre r\xc3\xa9f\xc3\xa9renc\xc3\xa9e dans cette partie de la requ\xc3\xaate. in /var/www/collec/collec-1.1.0/plugins/objetBDD-3.5/ObjetBDD.php:392\nStack trace:\n#0 /var/www/collec/collec-1.1.0/plugins/objetBDD-3.5/ObjetBDD.php(905): ObjetBDD->execute('select * from (...')\n#1 /var/www/collec/collec-1.1.0/modules/classes/object.class.php(208): ObjetBDD->getListeParam('select * from (...')\n#2 /var/www/collec/collec-1.1.0/modules/classes/object.class.php(450): Object->getForList(Array, ' order by  case...')\n#3 /var/www/collec/collec-1.1.0/modules/gestion/storage.php(144): Object->batchRead(' CS.28.C\\r\\n')\n#4 /var/www/collec/collec-1.1.0/framework/controller.php(450): include('/var/www/collec...')\n#5 /var/www/collec/collec-1.1.0/index.p in /var/www/collec/collec-1.1.0/plugins/objetBDD-3.5/ObjetBDD.php on line 392, referer: https://collec.epoc.u-bordeaux.fr/index.php?module=storageBatchOpen

**Comment by equinton** [comment]
Corrigé en version 1.1.0b
